language: node_js
node_js:
  - 8
before_install:
  - "npm update -g npm"
script:
  - npm test
  - npm run production-build
deploy:
  - provider: pages
    skip_cleanup: true
    repo: $GITHUB_PAGES_REPO
    github_token: $GITHUB_PROD_TOKEN
    local_dir: dist
    on:
      branch: master
      condition: $GITHUB_PAGES_REPO != '' && $GITHUB_PROD_TOKEN != ''